---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenyixuan.
--- DateTime: 2021/4/16 2:49 下午
---

local luna_json = require("lunajson")

member_list = {}

function run_gossip()
    local task = {
        PluginName = "gossip",
        Command = "run",
        Args = {
            SubCommands = null,
            Flags = null,
            KVs = null,
        },
        ExtraArgs = null,
        Result = null
    }
    print("任务table：")
    require("pl.pretty").dump(task)
    return runner(luna_json.encode(task))
end

function run_gossip_join(server_ip, members)
    local task = {
        PluginName = "gossip",
        Command = "run",
        Args = {
            SubCommands = { members },
            Flags = null,
            KVs = null,
        },
        ExtraArgs = null,
        Result = null
    }
    print("任务table：")
    require("pl.pretty").dump(task)
    local uuid = send(server_ip, "server", luna_json.encode(task))
    print("UUID is : ", uuid)
    local addr = getRst(uuid)
    print("Result is : ", addr)
    return addr
end

member_list[1] = run_gossip()
member_list[2] = run_gossip_join("127.0.0.1:4002", member_list[1])
--member_list[3] = run_gossip_join("127.0.0.1:4003", member_list[1])

print("gossip集群启动完毕")
for i, v in ipairs(member_list) do
    print("获取到gossip " .. i .. " 的ip：" .. v)
end

----local s1 = runner("gossip", "Set", "a b")
----print(s1)
--local s2 = runner("gossip", "Get", "a")
--print(s2)
----local s3 = runner("gossip", "Del", "a")
----print(s3)
--
--
--local s4 = runner("gossip", "Set", "x asdfasedf")
--print(s4)
--local s5 = runner("gossip", "Get", "x")
--print(s5)