---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alex.
--- DateTime: 2021/5/12 上午10:08
---
function main(a, b, c)
    print("=================================")
    print(a)
    print(b)
    print(c)
    print("=================================")
    return "abc"
end