---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alex.
--- DateTime: 2021/5/12 上午10:08
--- 介绍：测试调用脚本中的指定函数，使用"--func"指定函数名，不指定默认为"main"
--- 例子：lua-script args-demo.lua hello hi 你好
---
function main(a, b, c)
    print("=============== 函数main ==============")
    print(a)
    print(b)
    print(c)
    print("=============== 函数main ==============")
    return "执行完成"
end

function f1(a, b, c)
    print("=============== 函数f1 ==================")
    print(a)
    print(b)
    print(c)
    print("=============== 函数f1 ==================")
    return "执行完成"
end