---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alex.
--- DateTime: 2021/3/25 上午1:30
---

local decorators = {}
local m = setmetatable({}, {__newindex = function(t, k, v)
    if 'function' == type(v) then
        for i = #decorators, 1, -1 do
            v = decorators[i](k, v)
            decorators[i] = nil
        end
    end
    rawset(t, k, v)
end})

local function AT(f)
    table.insert(decorators, f)
end

local function decorator()
    AT(function(fname, f)
        return function(x)
            print(string.format('call %s', fname))
            return string.format("The 2nd power of %s is %s", x, f(x))
        end
    end)
end

decorator()
function m.foo(x)
    return x ^ 2
end
