---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenyixuan.
--- DateTime: 2021/4/12 6:51 下午
---

print("this is no function")

c = 12

function main()
    print("this is main function")
end

function add(a, b)
    return a + b, a - b
end

function result()
    d = {"abc", "def"}
    d[1] = "lll"
    d["1"] = "kkk"
    d["hao"] = "de"
    return d
end