---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenyixuan.
--- DateTime: 2021/3/23 5:28 下午
---
print("hello world")
local s = [[{
  "name": "小明",
  "age": 14,
  "gender": true,
  "height": 1.65,
  "grade": null,
  "middle-school": "\"W3C\" Middle School",
  "skills": [
    "JavaScript",
    "Java",
    "Python",
    "Lisp"
  ]
}]]
print(package.path)
print(s)
local lunajson = require("lunajson")
local jsonstr = '{"Hello":["lunajson",1.5]}'
local t = lunajson.decode(jsonstr)
print(type(t))
print(t.Hello[2]) -- prints 1.5
j = lunajson.encode(t)
print(type(j))
print(j) -- prints {"Hello":["lunajson",1.5]}

result = 12

t = {"ll", "kk"}
t["a"] = "b"
print(t.a)

--function result()
--    print(result)
--    return "hi jack!"
--end