---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenyixuan.
--- DateTime: 2021/4/15 3:20 下午
---

--package.path = "/Users/chenyixuan/SyncThings/MyCode/Go/src/meepo/lua/module/?.lua;"..package.path

local go_utils = require("go-utils")
local sys_config_table = go_utils.get_sys_config()
print(sys_config_table.WorkDirAbs)

local utils = require("utils")
local pl_path = require("pl.path")
local config_path = pl_path.join(sys_config_table.WorkDirAbs, "config/gossip2.yml")
local config = utils.get_config(config_path)
print(config.port)

local luna_json = require("lunajson")

local gossip_config = {
    port = config.port,
    members = "192.168.42.10:53664"
}

local s = runnerEx("gossip", "Run", luna_json.encode(gossip_config))