---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alex.
--- DateTime: 2021/3/24 上午12:55
---
local s = runnerEx("show", "Net", "")
print(s)
local luna_json = require("lunajson")
local t = luna_json.decode(s)
print(t[1].name)