---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenyixuan.
--- DateTime: 2021/4/15 6:09 下午
---

local go_utils = {version = "0.1"}
luna_json = require("lunajson")

function go_utils.get_sys_config()
    sys_config = getConfig()
    local sys_config_table = luna_json.decode(sys_config)
    return sys_config_table
end

return go_utils