---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenyixuan.
--- DateTime: 2021/4/15 6:09 下午
---

local utils = {version = "0.1"}
yaml = require("yaml")

function utils.get_config(config_path)
    local file = io.open(config_path, "r")
    --在gopher-lua的虚拟机里，read的参数必须以"*"开头
    local config_string = file:read('*a')
    file:close()
    return yaml.eval(config_string)
end

return utils